function PlotRawData(experiment_data)
raw_data = GetRawData(experiment_data);
figure(100)
subplot(2,2,1)
plot(GetTimestamps(experiment_data), raw_data(1,:), 'Color', "#D95319")
subtitle('Joint 0 primary encoder')
subplot(2,2,2)
plot(GetTimestamps(experiment_data), raw_data(2,:), 'Color', "#D95319")
subtitle('Joint 1 primary encoder')
subplot(2,2,3)
plot(GetTimestamps(experiment_data), raw_data(3,:))
subtitle('Joint 0 secondary encoder')
subplot(2,2,4)
plot(GetTimestamps(experiment_data), raw_data(4,:))
subtitle('Joint 1 secondary encoder')
sgtitle('Raw data')
end