function PlotMotorStates(experiment_data)
    motors = DefineMotorStruct(experiment_data);
    figure(98)
    subplot(2,2,1)
    plot(GetTimestamps(experiment_data), motors.positions)
    title('Motors position')
    legend('Motor 0 (MRIE)', 'Motor 1 (MRIE)')
    subplot(2,2,2)
    plot(GetTimestamps(experiment_data), motors.velocities)
    title('Motors velocity')
    legend('Motor 0 (MRIE)', 'Motor 1 (MRIE)')
    sgtitle ('Joints position & Velocitiy')
    subplot(2,2,3)
    plot(GetTimestamps(experiment_data), motors.currents)
    title('Motors current')
    legend('Motor 0 (MRIE)', 'Motor 1 (MRIE)')
    subplot(2,2,4)
    plot(GetTimestamps(experiment_data), motors.PWM)
    title('Motors PWM')
    legend('Motor 0 (MRIE)', 'Motor 1 (MRIE)')
    sgtitle ('Motors position & Velocitiy')
end